disabled_rules:
  - todo
  - file_header
  - function_parameter_count
  - missing_docs
  - sorted_enum_cases

opt_in_rules:
  - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  - array_init
  - async_without_await
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - discarded_notification_center_observer
  - duplicate_imports
  - empty_collection_literal
  - empty_count
  - empty_parentheses_with_trailing_closure
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fatal_error_message
  - file_name
  - first_where
  - force_unwrapping
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - incompatible_concurrency_annotation
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_call_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - period_spacing
  - prefer_condition_list
  - prefer_key_path
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - sorted_first_last
  - sorted_imports
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unhandled_throwing_task
  - unneeded_break_in_switch
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - weak_delegate
  - yoda_condition

analyzer_rules:
  - capture_variable
  - explicit_self
  - explicit_acl
  - explicit_top_level_acl
  - unused_declaration
  - unused_import

line_length:
  warning: 100
  error: 120
  ignores_comments: true
  ignores_urls: true

indentation_width:
  indentation_width: 2

explicit_self:
  severity: error

explicit_acl:
  severity: error

explicit_top_level_acl:
  severity: error

unused_declaration:
  severity: error

unused_import:
  severity: error

trailing_whitespace:
  severity: error
  ignores_empty_lines: false

vertical_whitespace:
  severity: error
  max_empty_lines: 1

colon:
  apply_to_dictionaries: false

comma:
  severity: error

force_try:
  severity: error

force_cast:
  severity: warning

implicitly_unwrapped_optional:
  severity: error

force_unwrapping:
  severity: error

cyclomatic_complexity:
  warning: 10
  error: 15
  ignores_case_statements: true

function_body_length:
  warning: 50
  error: 100

nesting:
  type_level:
    warning: 3
    error: 4

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 400
  error: 800
  ignore_comment_only_lines: true

identifier_name:
  min_length: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - ID
    - UUID
    - x
    - y
    - i

type_name:
  min_length: 1
  max_length:
    warning: 60
    error: 80
  excluded:
    - ID
    - UUID

statement_position:
  statement_mode: default

overridden_super_call:
  severity: error

private_action:
  severity: error

private_outlet:
  severity: error

# missing_docs:
#   severity: warning
#   excluded:
#     - init
#     - deinit

implicit_getter:
  severity: error

last_where:
  severity: warning
first_where:
  severity: warning
empty_count:
  severity: error

number_separator:
  minimum_length: 5
